# Generated by Django 3.1.4 on 2022-01-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='owner_acctype',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='nodes',
            name='owner_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodes',
            name='owner_fullname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
