# Generated by Django 3.1.4 on 2022-01-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_auto_20220101_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='installed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
