# Generated by Django 3.1.4 on 2022-01-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_nodes_installed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='installed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
